function [beta,r2,adjr2,F,Ftest,t,ttest,residuals] = myregression(x,y)
n = size(x,1);
m = size(x,2);
b = ones(n,1);
x = [b,x];
beta = (x'*x)\(x'*y);
ttest = zeros(1,m+1);
sst=(y-mean(y))'*(y-mean(y));
sse=(y-x*beta)'*(y-x*beta);
ssr=sst-sse;
F=(ssr/m)/(sse/(n-m-1));
r2=ssr/sst;
adjr2=1-(n-1)/(n-m-1)*(1-r2);
Ftest=1-fcdf(F,m,n-m-1);
c=diag(inv(x'*x));
t=zeros(1,m+1);
sigma=sqrt(sse/(n-m-1));
for i=1:m+1
    t(i)=beta(i)/(sqrt(c(i))*sigma);
    ttest(i)=2*(1-tcdf(abs(t(i)),n-m-1));
end
residuals = y-x*beta;
